module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Media", [
      {
        CHANNEL_id: 1,
        title: "Video 1",
        description: "This is video one",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 1,
        accessType: "public",
        mediaType: "video",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 20034,
      },
      {
        CHANNEL_id: 1,
        title: "Post 1",
        description: "This is Post One",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 0,
        accessType: "private",
        mediaType: "post",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 234,
      },
      {
        CHANNEL_id: 1,
        title: "Video 2",
        description: "This is video Two",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 2034,
      },
      {
        CHANNEL_id: 2,
        title: "Video 4",
        description: "This is video Four",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 20034,
      },
      {
        CHANNEL_id: 2,
        title: "Video 5",
        description: "This is video Five",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 20034,
      },
      {
        CHANNEL_id: 3,
        title: "Video 6",
        description: "This is video Six",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 20034,
      },
      {
        CHANNEL_id: 3,
        title: "Live Stream",
        description: "This is Live Stream",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "video",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 2003400,
      },
      {
        CHANNEL_id: 1,
        title: "Post Two",
        description: "This is Post Two",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "post",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 20034,
      },
      {
        CHANNEL_id: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "video",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 20034,
      },
      {
        CHANNEL_id: 1,
        title: "Live Stream Three",
        description: "This is Live Stream Two",
        file: "https://www.youtube.com/watch?v=WNeLUngb-Xg",
        category: "People",
        ageRestriction: 0,
        accessType: "public",
        mediaType: "video",
        mediaTokenLimit: 0,
        dateCreated: "2023-07-17 13:41:50",
        views: 20034,
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Media", null, {});
  },
};
