module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Comments", [
      {
        USER_email: "waqasnazirm@gmail.com",
        MEDIA_id: 1,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqas3399nazir@gmail.com",
        MEDIA_id: 1,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 2",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "tariqbrohi@gmail.com",
        MEDIA_id: 1,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 3",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqarnazir@gmail.com",
        MEDIA_id: 1,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 4",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "hassannazir@gmail.com",
        MEDIA_id: 1,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 5",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqasnazirm@gmail.com",
        MEDIA_id: 2,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqas3399nazir@gmail.com",
        MEDIA_id: 2,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 2",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "tariqbrohi@gmail.com",
        MEDIA_id: 2,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 3",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqasnazirm@gmail.com",
        MEDIA_id: 3,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqas3399nazir@gmail.com",
        MEDIA_id: 3,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 2",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqasnazirm@gmail.com",
        MEDIA_id: 4,
        MEDIA_CHANNEL_id: 2,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqas3399nazir@gmail.com",
        MEDIA_id: 4,
        MEDIA_CHANNEL_id: 2,
        text: "Hello Channel 2",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "tariqbrohi@gmail.com",
        MEDIA_id: 4,
        MEDIA_CHANNEL_id: 2,
        text: "Hello Channel 3",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqasnazirm@gmail.com",
        MEDIA_id: 4,
        MEDIA_CHANNEL_id: 2,
        text: "Hello Channel 4",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqas3399nazir@gmail.com",
        MEDIA_id: 4,
        MEDIA_CHANNEL_id: 2,
        text: "Hello Channel 5",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "tariqbrohi@gmail.com",
        MEDIA_id: 4,
        MEDIA_CHANNEL_id: 2,
        text: "Hello Channel 6",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqasnazirm@gmail.com",
        MEDIA_id: 5,
        MEDIA_CHANNEL_id: 2,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqas3399nazir@gmail.com",
        MEDIA_id: 5,
        MEDIA_CHANNEL_id: 2,
        text: "Hello Channel 2",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "tariqbrohi@gmail.com",
        MEDIA_id: 6,
        MEDIA_CHANNEL_id: 3,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqasnazirm@gmail.com",
        MEDIA_id: 7,
        MEDIA_CHANNEL_id: 3,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqas3399nazir@gmail.com",
        MEDIA_id: 8,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "tariqbrohi@gmail.com",
        MEDIA_id: 9,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqasnazirm@gmail.com",
        MEDIA_id: 10,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 1",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "waqas3399nazir@gmail.com",
        MEDIA_id: 10,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 2",
        likes: 10,
        dislikes: 5,
      },
      {
        USER_email: "tariqbrohi@gmail.com",
        MEDIA_id: 10,
        MEDIA_CHANNEL_id: 1,
        text: "Hello Channel 3",
        likes: 10,
        dislikes: 5,
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Comments", null, {});
  },
};
