module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Media", [
      {
        channelId: 1,
        title: "Video 1",
        description: "This is video one",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "public",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Post 1",
        description: "This is Post One",
        file: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1742&q=80",
        categoryId: 2,
        ageRestriction: 0,
        accessType: "private",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 234,
      },
      {
        channelId: 1,
        title: "Video 2",
        description: "This is video Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2034,
      },
      {
        channelId: 2,
        title: "Video 4",
        description: "This is video Four",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 4,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 2,
        title: "Video 5",
        description: "This is video Five",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 5,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Video 6",
        description: "This is video Six",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 6,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Live Stream",
        description: "This is Live Stream",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 7,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2003400,
      },
      {
        channelId: 1,
        title: "Post Two",
        description: "This is Post Two",
        file: "https://images.unsplash.com/photo-1463620695885-8a91d87c53d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
        categoryId: 8,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 9,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "This is post title",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 9,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Three",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Video 1",
        description: "This is video one",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "public",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Post 1",
        description: "This is Post One",
        file: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1742&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "private",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 234,
      },
      {
        channelId: 1,
        title: "Video 2",
        description: "This is video Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2034,
      },
      {
        channelId: 2,
        title: "Video 4",
        description: "This is video Four",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 2,
        title: "Video 5",
        description: "This is video Five",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Video 6",
        description: "This is video Six",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Live Stream",
        description: "This is Live Stream",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2003400,
      },
      {
        channelId: 1,
        title: "Post Two",
        description: "This is Post Two",
        file: "https://images.unsplash.com/photo-1463620695885-8a91d87c53d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "This is post title",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 9,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Three",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Video 1",
        description: "This is video one",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "public",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Post 1",
        description: "This is Post One",
        file: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1742&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "private",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 234,
      },
      {
        channelId: 1,
        title: "Video 2",
        description: "This is video Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2034,
      },
      {
        channelId: 2,
        title: "Video 4",
        description: "This is video Four",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 2,
        title: "Video 5",
        description: "This is video Five",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Video 6",
        description: "This is video Six",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Live Stream",
        description: "This is Live Stream",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2003400,
      },
      {
        channelId: 1,
        title: "Post Two",
        description: "This is Post Two",
        file: "https://images.unsplash.com/photo-1463620695885-8a91d87c53d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "This is post title",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 9,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Three",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Video 1",
        description: "This is video one",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "public",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Post 1",
        description: "This is Post One",
        file: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1742&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "private",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 234,
      },
      {
        channelId: 1,
        title: "Video 2",
        description: "This is video Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2034,
      },
      {
        channelId: 2,
        title: "Video 4",
        description: "This is video Four",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 2,
        title: "Video 5",
        description: "This is video Five",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Video 6",
        description: "This is video Six",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Live Stream",
        description: "This is Live Stream",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2003400,
      },
      {
        channelId: 1,
        title: "Post Two",
        description: "This is Post Two",
        file: "https://images.unsplash.com/photo-1463620695885-8a91d87c53d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "This is post title",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 9,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Three",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Video 1",
        description: "This is video one",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "public",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Post 1",
        description: "This is Post One",
        file: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1742&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "private",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 234,
      },
      {
        channelId: 1,
        title: "Video 2",
        description: "This is video Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2034,
      },
      {
        channelId: 2,
        title: "Video 4",
        description: "This is video Four",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 2,
        title: "Video 5",
        description: "This is video Five",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Video 6",
        description: "This is video Six",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Live Stream",
        description: "This is Live Stream",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2003400,
      },
      {
        channelId: 1,
        title: "Post Two",
        description: "This is Post Two",
        file: "https://images.unsplash.com/photo-1463620695885-8a91d87c53d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "This is post title",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 9,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Three",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Video 1",
        description: "This is video one",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "public",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Post 1",
        description: "This is Post One",
        file: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1742&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "private",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 234,
      },
      {
        channelId: 1,
        title: "Video 2",
        description: "This is video Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2034,
      },
      {
        channelId: 2,
        title: "Video 4",
        description: "This is video Four",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "pay per view",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 2,
        title: "Video 5",
        description: "This is video Five",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Video 6",
        description: "This is video Six",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "private",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 3,
        title: "Live Stream",
        description: "This is Live Stream",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 2,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 2003400,
      },
      {
        channelId: 1,
        title: "Post Two",
        description: "This is Post Two",
        file: "https://images.unsplash.com/photo-1463620695885-8a91d87c53d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
        categoryId: 3,
        ageRestriction: 1,
        accessType: "subscription",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "video",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "This is post title",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "post",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Two",
        description: "This is Live Stream Two",
        file: "https://player.thetavideoapi.com/video/video_0g6x665yin0y95f3vfd3ctp84m",
        categoryId: 9,
        ageRestriction: 0,
        accessType: "token gate",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
      {
        channelId: 1,
        title: "Live Stream Three",
        description: "This is Live Stream Two",
        file: "https://images.unsplash.com/photo-1455894127589-22f75500213a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1574&q=80",
        categoryId: 1,
        ageRestriction: 0,
        accessType: "public",
        mediaType: "liveStream",
        mediaTokenLimit: 0,
        views: 20034,
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Media", null, {});
  },
};
